// find -printf "%y %p\n"

export const aksStoreDemoFiles = `
d .
d ./.devcontainer
f ./.devcontainer/devcontainer.json
f ./.devcontainer/installMoreTools.sh
f ./.dockerignore
d ./.git
f ./.git/config
f ./.git/description
f ./.git/HEAD
d ./.git/hooks
f ./.git/hooks/applypatch-msg.sample
f ./.git/hooks/commit-msg.sample
f ./.git/hooks/fsmonitor-watchman.sample
f ./.git/hooks/post-update.sample
f ./.git/hooks/pre-applypatch.sample
f ./.git/hooks/pre-commit.sample
f ./.git/hooks/pre-merge-commit.sample
f ./.git/hooks/pre-push.sample
f ./.git/hooks/pre-rebase.sample
f ./.git/hooks/pre-receive.sample
f ./.git/hooks/prepare-commit-msg.sample
f ./.git/hooks/push-to-checkout.sample
f ./.git/hooks/sendemail-validate.sample
f ./.git/hooks/update.sample
f ./.git/index
d ./.git/info
f ./.git/info/exclude
d ./.git/logs
f ./.git/logs/HEAD
d ./.git/logs/refs
d ./.git/logs/refs/heads
f ./.git/logs/refs/heads/main
d ./.git/logs/refs/remotes
d ./.git/logs/refs/remotes/origin
f ./.git/logs/refs/remotes/origin/HEAD
d ./.git/objects
d ./.git/objects/info
d ./.git/objects/pack
f ./.git/objects/pack/pack-a70ea8891cd2ad9a04de7d67f8af3b6a82de1a97.idx
f ./.git/objects/pack/pack-a70ea8891cd2ad9a04de7d67f8af3b6a82de1a97.pack
f ./.git/objects/pack/pack-a70ea8891cd2ad9a04de7d67f8af3b6a82de1a97.rev
f ./.git/packed-refs
d ./.git/refs
d ./.git/refs/heads
f ./.git/refs/heads/main
d ./.git/refs/remotes
d ./.git/refs/remotes/origin
f ./.git/refs/remotes/origin/HEAD
d ./.git/refs/tags
d ./.github
f ./.github/CODE_OF_CONDUCT.md
d ./.github/ISSUE_TEMPLATE
f ./.github/ISSUE_TEMPLATE/bug_report.md
f ./.github/ISSUE_TEMPLATE/feature_request.md
f ./.github/ISSUE_TEMPLATE.md
f ./.github/PULL_REQUEST_TEMPLATE.md
d ./.github/workflows
f ./.github/workflows/package-ai-service.yaml
f ./.github/workflows/package-makeline-service.yaml
f ./.github/workflows/package-order-service.yaml
f ./.github/workflows/package-product-service.yaml
f ./.github/workflows/package-store-admin.yaml
f ./.github/workflows/package-store-front.yaml
f ./.github/workflows/package-virtual-customer.yaml
f ./.github/workflows/package-virtual-worker.yaml
f ./.github/workflows/release-container-images.yaml
f ./.gitignore
f ./ai-service.yaml
f ./aks-store-all-in-one.yaml
f ./aks-store-quickstart.yaml
d ./assets
f ./assets/demo-arch-with-openai.png
f ./assets/demo-arch.png
f ./CHANGELOG.md
f ./CONTRIBUTING.md
f ./docker-compose-quickstart.yml
f ./docker-compose.yml
f ./LICENSE.md
f ./Makefile
f ./rabbitmq_enabled_plugins
f ./README.md
d ./src
d ./src/ai-service
f ./src/ai-service/.dockerignore
f ./src/ai-service/.gitignore
f ./src/ai-service/Dockerfile
f ./src/ai-service/main.py
f ./src/ai-service/README.md
f ./src/ai-service/requirements.txt
d ./src/ai-service/routers
f ./src/ai-service/routers/.env.example
f ./src/ai-service/routers/description_generator.py
f ./src/ai-service/routers/__init__.py
d ./src/ai-service/skills
d ./src/ai-service/skills/ProductSkill
d ./src/ai-service/skills/ProductSkill/Description
f ./src/ai-service/skills/ProductSkill/Description/config.json
f ./src/ai-service/skills/ProductSkill/Description/skprompt.txt
f ./src/ai-service/test-ai-service.http
d ./src/makeline-service
f ./src/makeline-service/.gitignore
f ./src/makeline-service/docker-compose.yml
f ./src/makeline-service/Dockerfile
f ./src/makeline-service/go.mod
f ./src/makeline-service/go.sum
f ./src/makeline-service/main.go
f ./src/makeline-service/mongodb.go
f ./src/makeline-service/README.md
f ./src/makeline-service/test-makeline-service.http
d ./src/order-service
f ./src/order-service/.dockerignore
f ./src/order-service/.gitignore
f ./src/order-service/app.js
f ./src/order-service/docker-compose.yml
f ./src/order-service/Dockerfile
f ./src/order-service/package-lock.json
f ./src/order-service/package.json
d ./src/order-service/plugins
f ./src/order-service/plugins/messagequeue.js
f ./src/order-service/plugins/README.md
f ./src/order-service/plugins/sensible.js
f ./src/order-service/plugins/support.js
f ./src/order-service/README.md
d ./src/order-service/routes
d ./src/order-service/routes/example
f ./src/order-service/routes/example/index.js
f ./src/order-service/routes/README.md
f ./src/order-service/routes/root.js
d ./src/order-service/test
f ./src/order-service/test/helper.js
d ./src/order-service/test/plugins
f ./src/order-service/test/plugins/support.test.js
d ./src/order-service/test/routes
f ./src/order-service/test/routes/example.test.js
f ./src/order-service/test/routes/root.test.js
f ./src/order-service/test-order-service.http
d ./src/product-service
f ./src/product-service/.dockerignore
f ./src/product-service/.gitignore
f ./src/product-service/Cargo.lock
f ./src/product-service/Cargo.toml
f ./src/product-service/Dockerfile
f ./src/product-service/README.md
d ./src/product-service/src
f ./src/product-service/src/main.rs
f ./src/product-service/test-product-service.http
d ./src/store-admin
f ./src/store-admin/.dockerignore
f ./src/store-admin/.gitignore
f ./src/store-admin/babel.config.js
f ./src/store-admin/docker-compose.yml
f ./src/store-admin/Dockerfile
f ./src/store-admin/jsconfig.json
f ./src/store-admin/nginx.conf
f ./src/store-admin/package-lock.json
f ./src/store-admin/package.json
d ./src/store-admin/public
f ./src/store-admin/public/favicon.ico
f ./src/store-admin/public/index.html
f ./src/store-admin/public/placeholder.png
f ./src/store-admin/README.md
d ./src/store-admin/src
f ./src/store-admin/src/App.vue
d ./src/store-admin/src/assets
f ./src/store-admin/src/assets/logo.png
d ./src/store-admin/src/components
f ./src/store-admin/src/components/OrderDetail.vue
f ./src/store-admin/src/components/OrderList.vue
f ./src/store-admin/src/components/ProductDetail.vue
f ./src/store-admin/src/components/ProductForm.vue
f ./src/store-admin/src/components/ProductList.vue
f ./src/store-admin/src/components/TopNav.vue
f ./src/store-admin/src/main.js
f ./src/store-admin/src/router.js
f ./src/store-admin/vue.config.js
d ./src/store-front
f ./src/store-front/.dockerignore
f ./src/store-front/.gitignore
f ./src/store-front/babel.config.js
f ./src/store-front/docker-compose.yml
f ./src/store-front/Dockerfile
f ./src/store-front/jsconfig.json
f ./src/store-front/nginx.conf
f ./src/store-front/package-lock.json
f ./src/store-front/package.json
d ./src/store-front/public
f ./src/store-front/public/favicon.ico
f ./src/store-front/public/index.html
f ./src/store-front/public/placeholder.png
f ./src/store-front/README.md
d ./src/store-front/src
f ./src/store-front/src/App.vue
d ./src/store-front/src/assets
f ./src/store-front/src/assets/404.jpg
d ./src/store-front/src/components
f ./src/store-front/src/components/ProductCard.vue
f ./src/store-front/src/components/ProductDetail.vue
f ./src/store-front/src/components/ProductList.vue
f ./src/store-front/src/components/ShoppingCart.vue
f ./src/store-front/src/components/TopNav.vue
f ./src/store-front/src/main.js
f ./src/store-front/src/router.js
f ./src/store-front/vue.config.js
d ./src/virtual-customer
f ./src/virtual-customer/.dockerignore
f ./src/virtual-customer/.gitignore
f ./src/virtual-customer/Cargo.lock
f ./src/virtual-customer/Cargo.toml
f ./src/virtual-customer/docker-compose.yml
f ./src/virtual-customer/Dockerfile
f ./src/virtual-customer/README.md
d ./src/virtual-customer/src
f ./src/virtual-customer/src/main.rs
d ./src/virtual-worker
f ./src/virtual-worker/.dockerignore
f ./src/virtual-worker/.gitignore
f ./src/virtual-worker/Cargo.lock
f ./src/virtual-worker/Cargo.toml
f ./src/virtual-worker/docker-compose.yml
f ./src/virtual-worker/Dockerfile
f ./src/virtual-worker/README.md
d ./src/virtual-worker/src
f ./src/virtual-worker/src/main.rs

`;
